name: docker-bake
description: An action to build and publish docker images using docker bake

inputs:
  cache-branches:
    description: List of branches that trigger publishing to cache. Defaults to the repository default branch.
    default: '${{ github.event.repository.default_branch }}'
  file:
    description: Path to Docker Bake file(s)
    default: './docker-bake.hcl'
  force-push:
    description: When 'true', force push to registry even if current branch is not in push-branches
    default: 'false'
  push-branches:
    description: List of branches that trigger publishing of images to registry. Defaults to the repository default branch.
    default: '${{ github.event.repository.default_branch }}'
  targets:
    description: List of bake targets
    default: 'ci'
    required: false

outputs:
  metadata:
    description: Build result metadata
    value: ${{ steps.bake.outputs.metadata }}

runs:
  using: "composite"
  steps:
    - name: Setup QEMU
      uses: docker/setup-qemu-action@49b3bc8e6bdd4a60e6116a5414239cba5943d3cf # v3.2.0

    - name: Setup Buildx
      uses: docker/setup-buildx-action@6524bf65af31da8d45b59e8c27de4bd072b392f5 # v3.8.0

    - name: Gather Image Labels and Tags
      id: meta
      uses: docker/metadata-action@369eb591f429131d6889c46b94e711f089e6ca96 # v5.6.1
      with:
        tags: |
          type=schedule,priority=10
          type=ref,event=tag,priority=9
          type=sha,format=short,prefix=commit-,priority=8
          type=raw,value=build-{{date 'YYYYMMDD-HHmmss'}},priority=6
          type=ref,event=pr,priority=5
          type=ref,event=branch,prefix=branch-,priority=5

    - id: input-parser
      uses: actions/github-script@v7
      with:
        script: |
          const cacheBranches = '${{ inputs.cache-branches }}'.split(/[\n,]/);
          const pushBranches = '${{ inputs.push-branches }}'.split(/[\n,]/);
          core.setOutput('cache-branches', JSON.stringify(cacheBranches));
          core.setOutput('push-branches', JSON.stringify(pushBranches));
          core.setOutput('cache', cacheBranches.includes('${{ github.ref_name }}'));
          core.setOutput('push', '${{ inputs.force-push }}' == 'true' || pushBranches.includes('${{ github.ref_name }}'));

    - name: Build and Publish
      id: bake
      uses: docker/bake-action@3fc70e1131fee40a422dd8dd0ff22014ae20a1f3 # v5.11.0
      env:
        DOCKER_BUILD_RECORD_UPLOAD: 'false'
      with:
        push: ${{ steps.input-parser.outputs.push }}
        files: |
          ${{ inputs.file }}
          ${{ steps.meta.outputs.bake-file }}
        targets: '${{ inputs.targets }}'
        # we disable all cache (*.cache-to=) if not on a cache branch so as not to pollute it
        set: |
          ${{ steps.input-parser.outputs.cache == 'true' && '' || '*.cache-to=' }} 
     
